SELECT DATE_FORMAT(NOW(), '%d/%m/%Y') AS formatted_date;

CREATE TABLE users(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL,
    registerDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);